// This file is auto-generated by scripts/increment-build-numbers.js. Do not edit.
export const VERSION_INFO = {
<<<<<<< HEAD
  version: "1.2",
  androidBuild: 52,
  iosBuild: 169
=======
  version: "1.2.0",
  androidBuild: 57,
  iosBuild: 56
>>>>>>> 7dc1535 (Initial commit)
};
